# Generated by Django 4.2.8 on 2023-12-26 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Контактные данные',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50, verbose_name='Специализация')),
                ('qualification', models.CharField(max_length=50, verbose_name='Квалификация')),
                ('areas_of_practice', models.CharField(max_length=100, verbose_name='Зоны практики')),
                ('photo', models.TextField(verbose_name='Фото')),
                ('short_bio', models.TextField(verbose_name='Биография')),
                ('contact_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contactdetails')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.contactdetails')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('sex', models.CharField(max_length=10, verbose_name='Пол')),
                ('dob', models.DateTimeField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Роль')),
                ('admin_access', models.BooleanField(default=False, verbose_name='Администратор')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.people')),
            ],
            options={
                'verbose_name': 'Персонал',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('mark', models.IntegerField(verbose_name='Оценка')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctors')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patients')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('people_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.people')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.AddField(
            model_name='patients',
            name='people_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.people'),
        ),
        migrations.AddField(
            model_name='doctors',
            name='people_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.people'),
        ),
        migrations.CreateModel(
            name='AppointmentsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_days', models.CharField(max_length=50, verbose_name='Рабочие дни')),
                ('business_hours', models.CharField(max_length=50, verbose_name='Рабочие часы')),
                ('available_slots', models.CharField(max_length=50, verbose_name='Свободные места')),
                ('appointments_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.appointments')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctors')),
            ],
            options={
                'verbose_name': 'Расписание встречи',
                'verbose_name_plural': 'Расписание встреч',
            },
        ),
        migrations.AddField(
            model_name='appointments',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctors'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patients'),
        ),
    ]
