# Generated by Django 4.2.8 on 2023-12-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='qualification',
            field=models.CharField(max_length=64, verbose_name='Квалификация'),
        ),
    ]
