# Generated by Django 4.2.8 on 2023-12-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_doctors_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='people_id',
            new_name='people',
        ),
    ]
