# Generated by Django 4.2.8 on 2023-12-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_people_id_doctors_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='dob',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
