# Generated by Django 4.2.8 on 2023-12-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_people_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='password',
            field=models.CharField(default='<PASSWORD>', max_length=32, verbose_name='Пароль'),
        ),
    ]
