# Generated by Django 4.2.8 on 2023-12-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_people_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointmentsschedule',
            old_name='appointments_id',
            new_name='appointments',
        ),
        migrations.RenameField(
            model_name='appointmentsschedule',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='doctors',
            old_name='contact_details_id',
            new_name='contact_details',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='contact_details_id',
            new_name='contact_details',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='people_id',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='people_id',
            new_name='people',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='stuff',
            old_name='people_id',
            new_name='people',
        ),
    ]
